FROM debian:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && apt-get install -y curl python2 \
    && ln -s /usr/bin/python2 /usr/bin/python \
    && apt-get -y autoclean

RUN mkdir /usr/local/nvm
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 8.16.0
ENV NVM_INSTALL_PATH $NVM_DIR/versions/node/v$NODE_VERSION

RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_INSTALL_PATH/lib/node_modules
ENV PATH $NVM_INSTALL_PATH/bin:$PATH

RUN node -v
RUN npm -v

WORKDIR /higress

COPY . .

RUN npm config set registry https://registry.npmmirror.com
RUN npm install --save-dev @babel/core
RUN npm install docsite@1.3.8 -g --unsafe-perm
RUN npm i -g --unsafe-perm