site:
  name: Spring Cloud Alibaba
  site: 'https://sca.aliyun.com'
  base: '/'
  trailingSlash: 'always'
  websiteGithubUrl: 'https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/develop-astro-sca'
  githubUrl: 'https://github.com/alibaba/spring-cloud-alibaba'
  logoUrl: "https://img.alicdn.com/imgextra/i1/O1CN01hmeX5e1NWlvOeF6OE_!!6000000001578-2-tps-286-36.png"
  downloadEbooks: "https://developer.aliyun.com/ebook/7565?spm=a2c6h.20345107.ebook-index.55.63dd7863MiD2j0"

analytics:
  vendors:
    googleAnalytics:
      id: G-NP3B57ZGEF # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id: 8d45b13e5afb579f4083ee89048f70ac
      verification: code-wzq5sw7io3
    aesAnalytics:
      pid: b3kPns
    clarityAlalytics:
      id: l4jzj6wbhh


# Default SEO metadata
metadata:
  title:
    default: AstroWind
    template: '%s — AstroWind'
  description: "\U0001F680 Suitable for Startups, Small Business, Sass Websites, Professional Portfolios, Marketing Websites, Landing Pages & Blogs."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AstroWind
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image


ui:
  colors:
    # 主按钮颜色，一般为主色中间的颜色
    primary: "#5DC07E" # green-08
    # 次按钮的颜色，一般为灰色调最浅颜色
    secondary: "#F6F8F8" #moss-01
    # 强调色。"Header"中的联系我们
    accent: "#418B47" #green-10
    # 中性色。作为大标题的字体颜色
    neutral: "#0C1D0D" #green-14
    # 基础色，用做首页的背景色1
    base-100: "#F6F8F8" # moss-01
    # 信息颜色。Headline的上方小字, Fotter商标字体颜色
    info: "#666963" #gray-10
    # 成功。 Header的分割符、主要特性中的分割符、companiesfeedback中的isGray的背景颜色
    success: "#7E9B99" #moss-08
    # 警告。header中的toggle-trigger-atc颜色
    warning: "#597371" #moss-10
    # 错误。搜索等组件的bgcolor
    error: "#EBEFEF" #moss-02
    # 静音 companiesfeedback中的isLight的背景颜色
    muted: "#D3EDD5" #green-03
    # 搜索/语言切换组件的文字颜色
    link: "#DDE4E4" #moss-03
    white: "#FFFFFF"
    # blue
    blue-01: "#EDF2FC" 
    blue-02: "#E0E9FB" 
    blue-03: "#C6D6F7" 
    blue-04: "#A6BFF2" 
    blue-05: "#8BABE9" 
    blue-06: "#7097E6" 
    blue-07: "#567BE1" 
    blue-08: "#3D57DA" 
    blue-09: "#2C46C9" 
    blue-10: "#1F36AD" 
    blue-11: "#162B92" 
    blue-12: "#0D1A59" 
    blue-13: "#0B1337" 
    blue-14: "#070B22" 
    blue-15: "#030611" 
    # gray
    gray-01: "#F4F4F6" 
    gray-02: "#EBECEF" 
    gray-03: "#DDDEE4" 
    gray-04: "#C7C9D1" 
    gray-05: "#B3B6C1" 
    gray-06: "#A3A6B3" 
    gray-07: "#9295A5" 
    gray-08: "#818598" 
    gray-09: "#6E7587" 
    gray-10: "#5C6170" 
    gray-11: "#4C505D" 
    gray-12: "#2E3038" 
    gray-13: "#1E1F24" 
    gray-14: "#121316" 
    gray-15: "#0A0A0A" 